/* Generated by Yosys 0.9 (git sha1 1979e0b) */

module \$paramod\counter\N=4 (clk, nrst, enable, clear, wrap, max, count, at_max);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  output at_max;
  input clear;
  input clk;
  output [3:0] count;
  input enable;
  input [3:0] max;
  wire [3:0] next_count;
  input nrst;
  input wrap;
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(count[1]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(wrap),
    .Y(_01_)
  );
  sky130_fd_sc_hd__xor2_1 _18_ (
    .A(max[3]),
    .B(count[3]),
    .X(_02_)
  );
  sky130_fd_sc_hd__xor2_1 _19_ (
    .A(max[2]),
    .B(count[2]),
    .X(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _20_ (
    .A(count[0]),
    .B(max[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__xor2_1 _21_ (
    .A(max[1]),
    .B(count[1]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor4_1 _22_ (
    .A(_02_),
    .B(_03_),
    .C(_04_),
    .D(_05_),
    .Y(at_max)
  );
  sky130_fd_sc_hd__nand2_1 _23_ (
    .A(count[0]),
    .B(enable),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21oi_1 _24_ (
    .A1(_01_),
    .A2(at_max),
    .B1(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _25_ (
    .A(enable),
    .SLEEP(at_max),
    .X(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _26_ (
    .A(count[0]),
    .B(_08_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor3_1 _27_ (
    .A(clear),
    .B(_07_),
    .C(_09_),
    .Y(next_count[0])
  );
  sky130_fd_sc_hd__a211oi_1 _28_ (
    .A1(_01_),
    .A2(at_max),
    .B1(_06_),
    .C1(_00_),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a31o_1 _29_ (
    .A1(wrap),
    .A2(enable),
    .A3(at_max),
    .B1(clear),
    .X(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _30_ (
    .A(count[1]),
    .B(_07_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__nor3_1 _31_ (
    .A(_10_),
    .B(_11_),
    .C(_12_),
    .Y(next_count[1])
  );
  sky130_fd_sc_hd__xnor2_1 _32_ (
    .A(count[2]),
    .B(_10_),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor2_1 _33_ (
    .A(_11_),
    .B(_13_),
    .Y(next_count[2])
  );
  sky130_fd_sc_hd__and3_1 _34_ (
    .A(count[2]),
    .B(count[3]),
    .C(_10_),
    .X(_14_)
  );
  sky130_fd_sc_hd__a21oi_1 _35_ (
    .A1(count[2]),
    .A2(_10_),
    .B1(count[3]),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor3_1 _36_ (
    .A(_11_),
    .B(_14_),
    .C(_15_),
    .Y(next_count[3])
  );
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(next_count[0]),
    .Q(count[0]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(next_count[1]),
    .Q(count[1]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(next_count[2]),
    .Q(count[2]),
    .RESET_B(nrst)
  );
  sky130_fd_sc_hd__dfrtp_1 _40_ (
    .CLK(clk),
    .D(next_count[3]),
    .Q(count[3]),
    .RESET_B(nrst)
  );
endmodule

module counter_4(clk, nrst, enable, clear, wrap, max, count, at_max);
  output at_max;
  input clear;
  input clk;
  output [3:0] count;
  input enable;
  input [3:0] max;
  input nrst;
  input wrap;
  \$paramod\counter\N=4  COUNTER_4 (
    .at_max(at_max),
    .clear(clear),
    .clk(clk),
    .count(count),
    .enable(enable),
    .max(max),
    .nrst(nrst),
    .wrap(wrap)
  );
endmodule
